Repository BeNew98/DeathDoor, pull requests merged in 2023-10, with the labels that each got.

#157 이수정 feat : 플레이어, 피직스 업데이트
  GameEngineContents/ContentsEnum.h
  GameEngineContents/EnemyFirePlant.cpp
  GameEngineContents/EnemyFirePlant.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/GlobalValue.h
  GameEngineContents/PhysXCustom.cpp
  GameEngineContents/Player.cpp
  GameEngineContents/Player.h
  GameEngineContents/PlayerAttackRange.cpp
  GameEngineContents/PlayerAttackRange.h
  GameEngineContents/PlayerDefinition.h
  GameEngineContents/PlayerFSM.cpp
  GameEngineContents/PreCompileHeader.cpp
  GameEngineCore/GameEngineActor.h
Labels: enhancement

#161 GlowEffect 추가
  ContentResources/ContentsShader/AllBlur7x7.hlsl
  ContentResources/ContentsShader/ContentAniMeshDeffered.hlsl
  ContentResources/ContentsShader/ContentAnitMeshForward.hlsl
  ContentResources/ContentsShader/ContentMeshDeffered.hlsl
  ContentResources/ContentsShader/ContentMeshForward.hlsl
  ContentResources/ContentsShader/ContentTextureShader.hlsl
  ContentResources/ContentsShader/ContentsShader.vcxproj
  ContentResources/ContentsShader/ContentsShader.vcxproj.filters
  ContentResources/ContentsShader/DefferedColorMerge.hlsl
  ContentResources/ContentsShader/DetectMask.hlsl
  ContentResources/ContentsShader/LightMerge.hlsl
  ContentResources/ContentsShader/ResultRender.hlsl
  ContentResources/ContentsShader/쉐이더 사용법.txt
  GameEngineContents/ContentFBXRenderer.cpp
  GameEngineContents/ContentFBXRenderer.h
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/GlowEffect.cpp
  GameEngineContents/GlowEffect.h
  GameEngineContents/MyTest.cpp
  GameEngineContents/MyTest.h
  GameEngineContents/OfficeLevel.cpp
  GameEngineContents/PlayerInit.cpp
  GameEngineContents/PreCompileHeader.h
Labels: enhancement

#163 이수정 fix : 피직스 콜리전 체크 문제 임시 해결
  GameEngineContents/EnemyFirePlant.cpp
  GameEngineContents/PhysXCustom.cpp
  GameEngineContents/PreCompileHeader.cpp
  GameEngineCore/GameEngineActor.h
Labels: bug

#173 Develop
  ContentResources/ContentsShader/ContentsShader.vcxproj
  ContentResources/ContentsShader/ContentsShader.vcxproj.filters
  ContentResources/ContentsShader/GrayScale.hlsl
  ContentResources/ContentsShader/쉐이더 사용법.txt
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/GrayScaleEffect.cpp
  GameEngineContents/GrayScaleEffect.h
  GameEngineContents/OfficeLevel.cpp
  GameEngineContents/OfficeLevel.h
  GameEngineCore/GameEngineLevel.cpp
Labels: enhancement

#176 Develop
  ContentResources/ContentsShader/ContentsShader.vcxproj
  ContentResources/ContentsShader/ContentsShader.vcxproj.filters
  ContentResources/ContentsShader/FireShader.hlsl
  ContentResources/Texture/Fire/FireAlpha.png
  ContentResources/Texture/Fire/FireColor.png
  ContentResources/Texture/Fire/FireNoise.png
  GameEngineContents/ContentSpriteRenderer.cpp
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/FireObject.cpp
  GameEngineContents/FireObject.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
Labels: enhancement

#179 Develop
  GameEngineContents/ContentSpriteRenderer.cpp
  GameEngineContents/ContentSpriteRenderer.h
  GameEngineContents/ContentsCore.h
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/FireObject.cpp
  GameEngineContents/MyTest.cpp
Labels: enhancement

#180 Develop
  ContentResources/Texture/Fire/FireAlpha.png
  ContentResources/Texture/Fire/FireAlpha11.png
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/FireObject.cpp
  GameEngineContents/FireObject.h
Labels: enhancement

#185 허동석 add : Ruins_Wall fbx 추가 / feat : FrogBossLevel 임시 배치완료
  ContentResources/MapInfo/FrogBossLevel.csv
  ContentResources/MapInfo/FrogBossLevel.csvread.csv
  ContentResources/MapInfo/FrogBossLevel_Test.csv
  ContentResources/MapInfo/FrogBossLevel_Test.csvread.csv
  ContentResources/Mesh/Map/Fortress/Ruins_Wall.MeshFBX
  ContentResources/Mesh/Map/Fortress/Ruins_Wall.fbx
  GameEngineContents/FrogBossLevel.h
  GameEngineContents/FrogFloor.cpp
  GameEngineContents/FrogFloor.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/RuinsWall.cpp
  GameEngineContents/RuinsWall.h
Labels: AddFile

#204 Develop
  .gitignore
  ContentResources/ContentsShader/AllBlur7x7.hlsl
  ContentResources/ContentsShader/DetectMask.hlsl
  ContentResources/ContentsShader/LightMerge.hlsl
  GameEngineContents/ContentFBXRenderer.h
  GameEngineContents/ContentLevel.cpp
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/GlowEffect.cpp
  GameEngineContents/GlowEffect.h
Labels: enhancement

#205 허동석_feat : 수동컬링 렌더러 On,Off 여부 체크 완료, 트리거 충돌필터 추가 / add : 충돌체크용 fbx 추가
  ContentResources/MapInfo/FortressLevel_Fix.csv
  ContentResources/Mesh/Static/Map/Fortress/Culling_Trigger.MeshFBX
  ContentResources/Mesh/Static/Map/Fortress/Culling_Trigger.fbx
  GameEngineContents/ContentsEnum.h
  GameEngineContents/CullingManager.cpp
  GameEngineContents/CullingManager.h
  GameEngineContents/CullingObject.cpp
  GameEngineContents/CullingObject.h
  GameEngineContents/CullingTrigger.cpp
  GameEngineContents/CullingTrigger.h
  GameEngineContents/GlobalValue.cpp
  GameEngineContents/Map_Fortress.cpp
  GameEngineContents/Map_Fortress.h
  GameEngineContents/PhysXCustom.cpp
Labels: AddFile

#209 Develop
  ContentResources/ContentsShader/AllBlur7x7.hlsl
  ContentResources/ContentsShader/ContentsShader.vcxproj
  ContentResources/ContentsShader/ContentsShader.vcxproj.filters
  ContentResources/ContentsShader/DetectMask.hlsl
  ContentResources/ContentsShader/DustShader.hlsl
  ContentResources/ContentsShader/SwordTrailShader.hlsl
  ContentResources/Texture/Effect/Dust/DustNoise.png
  ContentResources/Texture/Effect/Dust/DustNoise11.png
  ContentResources/Texture/Effect/Fire/FireAlpha.png
  ContentResources/Texture/Effect/Fire/FireAlpha11.png
  ContentResources/Texture/Effect/Fire/FireColor.png
  ContentResources/Texture/Effect/Fire/FireNoise.png
  ContentResources/Texture/Effect/Mask/CrackMask.png
  ContentResources/Texture/Effect/Mask/CrackMask1.png
  ContentResources/Texture/Effect/Mask/CrackMask2.png
  ContentResources/Texture/Effect/Mask/CrackMask3.png
  ContentResources/Texture/Effect/Mask/CrackMask4.png
  ContentResources/Texture/Effect/Mask/MaskType1_0.png
  ContentResources/Texture/Effect/Mask/MaskType1_2.png
  ContentResources/Texture/Effect/Mask/MaskType1_3.png
  ContentResources/Texture/Effect/Mask/MaskType1_4.png
  ContentResources/Texture/Effect/Mask/MaskType2_0.png
  ContentResources/Texture/Effect/Mask/MaskType2_1.png
  ContentResources/Texture/Effect/Mask/MaskType2_2.png
  ContentResources/Texture/Effect/Mask/MaskType2_3.png
  ContentResources/Texture/Effect/Mask/WholeMask.png
  ContentResources/Texture/Effect/Mask/weaponsBlurMask.png
  ContentResources/Texture/Effect/RendererTexture/SwordTrail.png
  ContentResources/Texture/Effect/RendererTexture/SwordTrailMask.png
  ContentResources/Texture/Effect/RendererTexture/SwordTrailReverseMask.png
  EngineResources/Shader/DeferredCalLight.hlsl
  GameEngineContents/ContentLevel.cpp
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/Dust.cpp
  GameEngineContents/Dust.h
  GameEngineContents/DustRenderer.cpp
  GameEngineContents/DustRenderer.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/GlowEffect.cpp
  GameEngineContents/OfficeLevel.cpp
  GameEngineCore/GameEngineDevice.cpp
Labels: enhancement

#241 Develop
  ContentResources/Mesh/Static/Map/Fortress/Fortress_FullMap_NavMesh.MeshFBX
  ContentResources/Mesh/Static/Map/Fortress/Fortress_FullMap_NavMesh.fbx
  ContentResources/Mesh/Static/Map/Fortress/Fortress_NaviMesh.MeshFBX
  ContentResources/Mesh/Static/Map/Fortress/Fortress_NaviMesh.fbx
  ContentResources/Mesh/Static/Map/Fortress/Fortress_NaviMesh_Wall_Blender.MeshFBX
  ContentResources/Mesh/Static/Map/Fortress/Fortress_NaviMesh_Wall_Blender.fbx
  GameEngineContents/Map_Fortress.cpp
Labels: AddFile

#250 Develop
  ContentResources/ContentsShader/ContentAniMeshDeffered.hlsl
  ContentResources/ContentsShader/DetectMask.hlsl
  ContentResources/ContentsShader/DustParticle.hlsl
  ContentResources/Mesh/Animator/Boss/Frog/swampWeaponTex.png
  ContentResources/Mesh/Animator/Boss/Frog/swampWeaponTexMask.png
  ContentResources/Texture/Boss/Frog/swampWeaponTexMask.png
  GameEngineContents/ContentFBXRenderer.h
  GameEngineContents/ContentLevel.cpp
  GameEngineContents/ContentLevel.h
  GameEngineContents/DustParticle.cpp
  GameEngineContents/DustParticle.h
  GameEngineContents/MonsterAnimationTest.cpp
  GameEngineContents/PlayerTestLevel.cpp
Labels: enhancement, test, AddFile

#257 Develop
  ContentResources/ContentsShader/ContentTextureShader.hlsl
  ContentResources/ContentsShader/ContentsShader.vcxproj
  ContentResources/ContentsShader/ContentsShader.vcxproj.filters
  ContentResources/ContentsShader/DustParticle.hlsl
  ContentResources/ContentsShader/ParticleBasicShader.hlsl
  ContentResources/Texture/Boss/OldCrow/FeatherParticle.png
  ContentResources/Texture/Effect/Particle/ParticleNoise1.png
  ContentResources/Texture/Effect/Particle/ParticleNoise2.png
  ContentResources/Texture/Effect/Particle/PaticleAlpha.png
  ContentResources/Texture/MeshTexture/swampPillarTexture.png
  GameEngineContents/AttackBase.h
  GameEngineContents/Boss_OldCrow.cpp
  GameEngineContents/ContentFBXRenderer.h
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/DustParticle.cpp
  GameEngineContents/DustParticle.h
  GameEngineContents/EnemyBase.cpp
  GameEngineContents/EnemyGhoul.cpp
  GameEngineContents/FeatherParticle.cpp
  GameEngineContents/FeatherParticle.h
  GameEngineContents/Frog_Septre.cpp
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/GlowEffect.cpp
  GameEngineContents/ParticleBase.cpp
  GameEngineContents/PlayerAttackBomb.cpp
  GameEngineContents/PlayerAttackBomb.h
  GameEngineContents/PlayerAttackMagic.cpp
  GameEngineContents/PlayerAttackMagic.h
Labels: enhancement

#274 Develop
  ContentResources/ContentsShader/WaterShader.hlsl
  GameEngineContents/BossFrogMain.cpp
  GameEngineContents/BossTestLevel.cpp
  GameEngineContents/ContentLevel.cpp
  GameEngineContents/ContentLevel.h
  GameEngineContents/FortressLevel.cpp
  GameEngineContents/FrogBossLevel.cpp
  GameEngineContents/GlowEffect.cpp
  GameEngineContents/GlowEffect.h
  GameEngineContents/MapTestLevel.cpp
  GameEngineContents/OfficeLevel.cpp
  GameEngineContents/OldCrowLevel.cpp
  GameEngineContents/PlayerTestLevel.cpp
  GameEngineContents/WaterBox.cpp
  GameEngineContents/WaterBox.h
Labels: enhancement
