Repository BeNew98/DeathDoor, pull requests merged in 2023-09, with the labels that each got.

#73 오의현_feat : 마우스를 3D공간에 피킹하는 기능 추가
  GameEngineContents/Mouse.cpp
Labels: enhancement

#84 이수정 fix : arrow 애니메이션, 피직스 스케일, FSM변경 업데이트
  ContentResources/Mesh/Animations/Player/WithoutSword/Arrow.AnimationFBX
  ContentResources/Mesh/Animations/Player/WithoutSword/Arrow.fbx
  ContentResources/Mesh/Animations/Player/WithoutSword/Arrow_idle.AnimationFBX
  GameEngineContents/Player.cpp
  GameEngineContents/Player.h
  GameEngineContents/PlayerFSM.cpp
  GameEngineContents/PlayerInit.cpp
Labels: enhancement

#85 오의현 : Particle 관련 클래스 추가, Mouse 회전기능 개선
  ContentResources/Mesh/Map/Sphere.fbx
  ContentResources/Mesh/UI/Mouse.fbx
  ContentResources/Texture/CenterLevelBG.png
  ContentResources/Texture/UI/WhiteTexture.png
  GameEngineContents/ContentFBXUIRenderer.cpp
  GameEngineContents/ContentFBXUIRenderer.h
  GameEngineContents/DynamicParticleManager.cpp
  GameEngineContents/DynamicParticleManager.h
  GameEngineContents/Mouse.cpp
  GameEngineContents/Mouse.h
  GameEngineContents/MyTest.cpp
  GameEngineContents/MyTest.h
  GameEngineContents/ParticleManager.cpp
  GameEngineContents/ParticleManager.h
  GameEngineContents/ParticleRenderer.cpp
  GameEngineContents/ParticleRenderer.h
  GameEngineContents/ParticleStruct.h
  GameEngineContents/StaticParticleManager.cpp
  GameEngineContents/StaticParticleManager.h
  GameEngineContents/UITestLevel.cpp
  GameEngineContents/UITestLevel.h
Labels: enhancement, Annotation, AddFile

#88 이수정 feat : 플레이어 skill charge동안 방향전환 업데이트
  GameEngineContents/Player.cpp
  GameEngineContents/Player.h
  GameEngineContents/PlayerFSM.cpp
  GameEngineContents/PlayerInit.cpp
Labels: enhancement

#90 IMGUI 빛 조절 기능 추가
  GameEngineContents/LevelWindow.cpp
  GameEngineContents/Start_BackGround.cpp
  GameEngineCore/GameEngineLevel.h
Labels: enhancement

#98 이수정 refac : 플레이어 기능정리
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/Player.h
  GameEngineContents/PlayerBase.cpp
  GameEngineContents/PlayerBase.h
  GameEngineContents/PlayerDefinition.h
  GameEngineContents/PlayerFSM.cpp
Labels: enhancement, refactor

#100 허동석 add : 네비메쉬fbx 파일변경 및 오브젝트 배치 완료
  ContentResources/Mesh/Map/Map_Office_Navi.fbx
  ContentResources/Mesh/Map/Map_Office_Navi_Blend.MeshFBX
  ContentResources/Mesh/Map/Map_Office_Navi_Blend.fbx
  GameEngineContents/Map_Office.cpp
  GameEngineContents/Map_Office.h
Labels: AddFile

#106 허동석 feat, test : TransformWall 컴포넌트 Static 으로 변경, OfficeLevel 카메라 플레이…
  GameEngineContents/Map_Office.cpp
  GameEngineContents/OfficeLevel.cpp
  GameEngineContents/OfficeLevel.h
  GameEngineContents/Transform_Wall.cpp
Labels: test

#111 Develop
  ContentResources/ContentsShader/ContentsShader.vcxproj
  ContentResources/ContentsShader/ContentsShader.vcxproj.filters
  ContentResources/ContentsShader/FadeDeffered.hlsl
  ContentResources/Texture/Mask/MaskType1_0.png
  ContentResources/Texture/Mask/MaskType1_2.png
  ContentResources/Texture/Mask/MaskType1_3.png
  ContentResources/Texture/Mask/MaskType1_4.png
  ContentResources/Texture/Mask/MaskType2_0.png
  ContentResources/Texture/Mask/MaskType2_1.png
  ContentResources/Texture/Mask/MaskType2_2.png
  ContentResources/Texture/Mask/MaskType2_3.png
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/DynamicParticleManager.cpp
  GameEngineContents/MyTest.cpp
  GameEngineContents/MyTest.h
  GameEngineContents/ParticleRenderer.h
  GameEngineContents/ParticleStruct.h
  GameEngineContents/StaticParticleManager.cpp
  GameEngineCore/GameEngineRenderer.cpp
  GameEngineCore/GameEngineRenderer.h
Labels: enhancement

#112 Develop
  .github/ISSUE_TEMPLATE/github-issue-template.md
  ContentResources/ContentsShader/ContentAniMeshDeffered.hlsl
  ContentResources/ContentsShader/ContentsShader.vcxproj
  ContentResources/ContentsShader/ContentsShader.vcxproj.filters
  ContentResources/Mesh/Animations/TestBoss/OldCrow_Dash.AnimationFBX
  ContentResources/Mesh/Animations/TestBoss/OldCrow_Dash.fbx
  ContentResources/Mesh/TestBoss/OldCrow.FBX
  ContentResources/Mesh/TestBoss/OldCrow.MeshFBX
  ContentResources/Mesh/TestBoss/TOON_GRADIENT_easy.png
  ContentResources/Mesh/TestBoss/crowBossText.png
  ContentResources/Mesh/TestBoss/crowBossText_Cracks.png
  ContentResources/Mesh/TestBoss/crowFeathers_Cracks.png
  ContentResources/Mesh/TestBoss/feathersText.png
  ContentResources/Texture/Mask/CrackMask.png
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/MyTest.cpp
  GameEngineContents/MyTest.h
  GameEngineContents/UITestLevel.cpp
  GameEngineCore/GameEngineDevice.cpp
  GameEngineCore/GameEngineRenderer.cpp
  GameEngineCore/GameEngineRenderer.h
Labels: enhancement

#116 Shader 사용법 텍스트 추가, 쉐이더 기능 추가
  ContentResources/ContentsShader/ContentAniMeshDeffered.hlsl
  ContentResources/ContentsShader/ContentsShader.vcxproj
  ContentResources/ContentsShader/ContentsShader.vcxproj.filters
  ContentResources/ContentsShader/FadeDeffered.hlsl
  ContentResources/ContentsShader/쉐이더 사용법.txt
  ContentResources/Mesh/Animations/TestBoss/OldCrow_Dash.AnimationFBX
  ContentResources/Mesh/Animations/TestBoss/OldCrow_Dash.fbx
  ContentResources/Mesh/TestBoss/OldCrow.FBX
  ContentResources/Mesh/TestBoss/OldCrow.MeshFBX
  ContentResources/Mesh/TestBoss/TOON_GRADIENT_easy.png
  ContentResources/Mesh/TestBoss/crowBossText.png
  ContentResources/Mesh/TestBoss/crowBossText_Cracks.png
  ContentResources/Mesh/TestBoss/crowFeathers_Cracks.png
  ContentResources/Mesh/TestBoss/feathersText.png
  ContentResources/Texture/Mask/CrackMask.png
  ContentResources/Texture/Mask/CrackMask1.png
  GameEngineContents/MyTest.cpp
Labels: enhancement

#117 이수정 feat : E_FirePlant 기본구조 추가
  ContentResources/Mesh/Animations/Monster/_E_FIREPLANT/_E_FIREPLANT_BITE.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_FIREPLANT/_E_FIREPLANT_BITE.fbx
  ContentResources/Mesh/Animations/Monster/_E_FIREPLANT/_E_FIREPLANT_DIE.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_FIREPLANT/_E_FIREPLANT_DIE.fbx
  ContentResources/Mesh/Animations/Monster/_E_FIREPLANT/_E_FIREPLANT_IDLE.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_FIREPLANT/_E_FIREPLANT_IDLE.fbx
  ContentResources/Mesh/Characters/Monster/_E_FIREPLANT_MESH/CloudTexture.png
  ContentResources/Mesh/Characters/Monster/_E_FIREPLANT_MESH/TOON_GRADIENT_easy.png
  ContentResources/Mesh/Characters/Monster/_E_FIREPLANT_MESH/_E_FIREPLANT_MESH.MeshFBX
  ContentResources/Mesh/Characters/Monster/_E_FIREPLANT_MESH/_E_FIREPLANT_MESH.fbx
  ContentResources/Mesh/Characters/Monster/_E_FIREPLANT_MESH/circlenoise.png
  ContentResources/Mesh/Characters/Monster/_E_FIREPLANT_MESH/plantEnemy01Texture.png
  ContentResources/Mesh/Characters/Monster/test/Flower.MeshFBX
  ContentResources/Mesh/Characters/Monster/test/_E_PLANT.MeshFBX
  ContentResources/Mesh/Characters/Monster/test/_E_PLANT.fbx
  ContentResources/Mesh/Characters/Monster/test/plantEnemy02Texture.png
  GameEngineContents/EnemyBat.cpp
  GameEngineContents/EnemyBat.h
  GameEngineContents/EnemyFirePlant.cpp
  GameEngineContents/EnemyFirePlant.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/MapTestLevel.cpp
  GameEngineContents/MonsterAnimationTest.cpp
  GameEngineContents/Player.cpp
  GameEngineContents/Player.h
  GameEngineContents/PlayerInit.cpp
  GameEngineContents/PlayerTestLevel.cpp
Labels: enhancement

#118 Develop
  ContentResources/ContentsShader/ContentAniMeshDeffered.hlsl
  ContentResources/ContentsShader/FadeDeffered.hlsl
  ContentResources/ContentsShader/FadeShader.hlsl
  ContentResources/ContentsShader/쉐이더 사용법.txt
  GameEngineContents/ContentFBXRenderer.cpp
  GameEngineContents/ContentFBXRenderer.h
  GameEngineCore/GameEngineCore_Resources.cpp
Labels: enhancement, Annotation

#120 허동석 add : FortressLevel 네비메쉬 추가, 임시배치 완료
  ContentResources/MapInfo/FortressLevel.csv
  ContentResources/MapInfo/FortressLevel.csvread.csv
  ContentResources/MapInfo/OfficeLevel_Obj.csv
  ContentResources/MapInfo/OfficeLevel_Obj.csvread.csv
  ContentResources/Mesh/Map/Fortress/Fortrss_FullMap_Navi.MeshFBX
  ContentResources/Mesh/Map/Fortress/Fortrss_FullMap_Navi.fbx
  GameEngineContents/FortressLevel.cpp
  GameEngineContents/FortressLevel.h
  GameEngineContents/LevelWindow.cpp
  GameEngineContents/MapEditorLevel.cpp
  GameEngineContents/Map_Fortress.cpp
  GameEngineContents/Map_Fortress.h
Labels: AddFile

#122 허동석 add : 오브젝트 fbx 및 텍스쳐 추가 / feat : FortressLevel에서 사용할 Crate,Tile 클…
  ContentResources/Mesh/Map/Fortress/Crate.MeshFBX
  ContentResources/Mesh/Map/Fortress/Crate.fbm/planks_DIFF_Var04.png
  ContentResources/Mesh/Map/Fortress/Crate.fbx
  ContentResources/Mesh/Map/Fortress/FrogTile.MeshFBX
  ContentResources/Mesh/Map/Fortress/FrogTile.fbm/basicFloorVariation1Texture_Frog.png
  ContentResources/Mesh/Map/Fortress/FrogTile.fbx
  GameEngineContents/BossTestLevel.cpp
  GameEngineContents/Crate.cpp
  GameEngineContents/Crate.h
  GameEngineContents/FortressLevel.cpp
  GameEngineContents/FortressLevel.h
  GameEngineContents/Frog_Lever.cpp
  GameEngineContents/Frog_Lever.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/Map_Fortress.cpp
  GameEngineContents/SecretTile.cpp
  GameEngineContents/SecretTile.h
Labels: AddFile

#125 이수정 feat : E_GRUNT 기본 구조 추가
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_BREAK.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_BREAK.FBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_IDLE.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_IDLE.FBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_RUN.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_RUN.FBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_SLAM.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_SLAM.FBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_SWING.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_SWING.FBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_THROW.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_THROW.FBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_WALK.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE/_E_BRUTE_WALK.FBX
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_MESH/TOON_GRADIENT_easy.png
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_MESH/_E_BRUTE_MESH.FBX
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_MESH/_E_BRUTE_MESH.MeshFBX
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_MESH/bruteGruntTexture_Multi - 복사본.png
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_MESH/bruteGruntTexture_Multi.png
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_MESH/cracks_generic.png
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_MESH/shovelslash.png
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_MESH/sword_slash_extra.png
  GameEngineContents/EnemyBase.cpp
  GameEngineContents/EnemyBase.h
  GameEngineContents/EnemyBrute.cpp
  GameEngineContents/EnemyBrute.h
  GameEngineContents/EnemyDefinition.h
  GameEngineContents/EnemyGrunt.cpp
  GameEngineContents/EnemyGrunt.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/MonsterAnimationTest.cpp
Labels: enhancement

#126 Develop
  ContentResources/ContentsShader/ContentAniMeshDeffered.hlsl
  ContentResources/ContentsShader/ContentAnitMeshForward.hlsl
  ContentResources/ContentsShader/ContentsShader.vcxproj
  ContentResources/ContentsShader/ContentsShader.vcxproj.filters
  ContentResources/ContentsShader/FadeDeffered.hlsl
  ContentResources/ContentsShader/HorizonBlur.hlsl
  ContentResources/ContentsShader/VerticalBlur.hlsl
  ContentResources/ContentsShader/쉐이더 사용법.txt
  ContentResources/Texture/Mask/CrackMask.png
  ContentResources/Texture/Mask/CrackMask1.png
  ContentResources/Texture/Mask/CrackMask2.png
  ContentResources/Texture/Mask/CrackMask3.png
  ContentResources/Texture/Mask/CrackMask4.png
  GameEngineContents/ContentFBXRenderer.cpp
  GameEngineContents/ContentFBXRenderer.h
  GameEngineContents/Contents_Resources.cpp
Labels: enhancement

#127 Develop
  ContentResources/ContentsShader/ContentsShader.vcxproj
  ContentResources/ContentsShader/ContentsShader.vcxproj.filters
  EngineResources/Shader/FXAA.hlsl
  EngineResources/Shader/Shader.vcxproj
  EngineResources/Shader/Shader.vcxproj.filters
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/MyTest.cpp
  GameEngineContents/Start_BackGround.cpp
  GameEngineCore/GameEngineCore_Resources.cpp
  GameEngineCore/GameEngineLevel.cpp
  GameEngineCore/GameEngineLevel.h
Labels: enhancement

#135 이수정 feat : Enemey GHOUL 기본 구조 추가
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_DROWN.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_DROWN.fbx
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_HIT_BOW.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_HIT_BOW.fbx
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_IDLE.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_IDLE.FBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_IDLE_BOW.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_IDLE_BOW.FBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_IDLE_SWORD.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_IDLE_SWORD.FBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_RUN.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_RUN.FBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_RUN_BOW.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_RUN_BOW.FBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_RUN_SWORD.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_RUN_SWORD.FBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_SHOOT_BOW.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_SHOOT_BOW.fbx
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_SHOOT_BOW_RAPID.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_SHOOT_BOW_RAPID.fbx
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_WALK.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_GHOUL/_E_GHOUL_WALK.FBX
  ContentResources/Mesh/Characters/Monster/_E_GHOUL_MESH/GoolTexture.png
  ContentResources/Mesh/Characters/Monster/_E_GHOUL_MESH/TOON_GRADIENT_easy.png
  ContentResources/Mesh/Characters/Monster/_E_GHOUL_MESH/_E_GHOUL_MESH.FBX
  ContentResources/Mesh/Characters/Monster/_E_GHOUL_MESH/_E_GHOUL_MESH.MeshFBX
  ContentResources/Mesh/Characters/Monster/_E_GHOUL_MESH/cracks_generic.png
  GameEngineContents/EnemyBase.h
  GameEngineContents/EnemyBat.h
  GameEngineContents/EnemyBrute.h
  GameEngineContents/EnemyFirePlant.h
  GameEngineContents/EnemyGhoul.cpp
  GameEngineContents/EnemyGhoul.h
  GameEngineContents/EnemyGrunt.h
  GameEngineContents/EnemyMage.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/MapTestLevel.cpp
  GameEngineContents/MonsterAnimationTest.cpp
Labels: enhancement, AddFile

#138 포인트 라이트 추가
  ContentResources/ContentsShader/ContentAniMeshDeffered.hlsl
  ContentResources/ContentsShader/ContentMeshForward.hlsl
  ContentResources/ContentsShader/ContentMeshShader.hlsl
  ContentResources/ContentsShader/ContentsShader.vcxproj
  ContentResources/ContentsShader/ContentsShader.vcxproj.filters
  EngineResources/Shader/DeferredCalLight.hlsl
  EngineResources/Shader/DeferredMerge.hlsl
  EngineResources/Shader/Light.fx
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/MyTest.cpp
  GameEngineContents/UITestLevel.cpp
  GameEngineCore/GameEngineCamera.cpp
  GameEngineCore/GameEngineLevel.cpp
  GameEngineCore/GameEngineLevel.h
  GameEngineCore/GameEngineRenderer.cpp
  GameEngineCore/GameEngineRenderer.h
Labels: enhancement

#140 포워드렌더링의 빛계산을 버텍스쉐이더에서 하도록 변경
  ContentResources/ContentsShader/ContentAnitMeshForward.hlsl
  ContentResources/ContentsShader/ContentLight.fx
  ContentResources/ContentsShader/ContentMeshForward.hlsl
Labels: enhancement

#143 이수정 feat : 애니메이션 블랜드 기능 추가 업데이트
  GameEngineCore/GameEngineFBXRenderer.cpp
  GameEngineCore/GameEngineFBXRenderer.h
Labels: enhancement

#144 이수정 add : Enemy BruteGold 추가
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_BREAK.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_BREAK.FBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_IDLE.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_IDLE.FBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_RUN.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_RUN.FBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_SLAM.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_SLAM.FBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_SWING.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_SWING.FBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_THROW.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_THROW.FBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_WALK.AnimationFBX
  ContentResources/Mesh/Animations/Monster/_E_BRUTE_GOLD/_E_BRUTE_GOLD_WALK.FBX
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_GOLD_MESH/TOON_GRADIENT_easy.png
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_GOLD_MESH/_E_BRUTE_GOLD_MESH.FBX
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_GOLD_MESH/_E_BRUTE_GOLD_MESH.MeshFBX
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_GOLD_MESH/bruteGruntTexture_Multi.png
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_GOLD_MESH/cracks_generic.png
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_GOLD_MESH/shovelslash.png
  ContentResources/Mesh/Characters/Monster/_E_BRUTE_GOLD_MESH/sword_slash_extra.png
  GameEngineContents/EnemyBruteGold.cpp
  GameEngineContents/EnemyBruteGold.h
  GameEngineContents/EnemyDefinition.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/MapTestLevel.cpp
  GameEngineCore/GameEngineFBXRenderer.h
Labels: enhancement, AddFile

#146 이수정 fix : 캡슐 디버그랜더 변경
  EngineResources/Mesh/CapsuleDebugMesh.MeshFBX
  EngineResources/Mesh/CapsuleDebugMesh.fbx
  GameEngineContents/PhysXCapsuleComponent.cpp
  GameEngineCore/GameEngineCore_Resources.cpp
  GameEngineCore/GameEngineDebug3D.cpp
Labels: enhancement
