Repository BeNew98/DeathDoor, pull requests merged in 2023-08, with the labels that each got.

#10 이수정 feat : gui freecamera추가, setFBXMesh 예외 추가
  GameEngineContents/LevelWindow.cpp
  GameEngineContents/LevelWindow.h
  GameEngineCore/GameEngineCamera.h
  GameEngineCore/GameEngineFBXRenderer.cpp
Labels: enhancement

#12 이수정 feat : 엔진 업데이트 #11
  GameEngineBase/GameEngineBase.vcxproj
  GameEngineBase/GameEngineBase.vcxproj.filters
  GameEngineBase/GameEngineDispatcher.cpp
  GameEngineBase/GameEngineDispatcher.h
  GameEngineBase/GameEngineFile.h
  GameEngineBase/GameEngineNet.cpp
  GameEngineBase/GameEngineNet.h
  GameEngineBase/GameEngineNetObject.h
  GameEngineBase/GameEnginePacket.h
  GameEngineBase/GameEngineSerializer.h
  GameEngineBase/PrecompileHeader.h
  GameEngineContents/ConnectIDPacket.cpp
  GameEngineContents/ConnectIDPacket.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/ObjectUpdatePacket.cpp
  GameEngineContents/ObjectUpdatePacket.h
  GameEngineContents/PacketEnum.cpp
  GameEngineContents/PacketEnum.h
  GameEngineContents/ServerWindow.cpp
  GameEngineContents/ServerWindow.h
Labels: enhancement

#14 MapEditor기능 추가 #13
  App/imgui.ini
  ContentResources/Mesh/Characters/ActorFrozenBlock.fbx
  ContentResources/tmp/Cpytest.csv
  ContentResources/tmp/test.csv
  GameEngineContents/ContentsCore.cpp
  GameEngineContents/ContentsFBXRenderer.cpp
  GameEngineContents/ContentsFBXRenderer.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/LevelWindow.cpp
  GameEngineContents/MapEditGlobalValue.h
  GameEngineContents/MapEditorLevel.cpp
  GameEngineContents/MapEditorLevel.h
  GameEngineContents/MapEditorWindow.cpp
  GameEngineContents/MapEditorWindow.h
  GameEngineContents/ProcessMapInfo.cpp
  GameEngineContents/ProcessMapInfo.h
  GameEngineCore/GameEngineGUI.cpp
  GameEngineCore/GameEngineLevel.h
Labels: enhancement

#18 이수정 feat : Map Editor 기능 추가 #15 #17
  App/imgui.ini
  ContentResources/MapInfo/Cpytest.csv
  ContentResources/MapInfo/test.csv
  GameEngineBase/GameEngineNet.cpp
  GameEngineContents/ContentsFBXRenderer.cpp
  GameEngineContents/ContentsFBXRenderer.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/MapEditorWindow.cpp
  GameEngineContents/MapEditorWindow.h
  GameEngineContents/PinActor.cpp
  GameEngineContents/PinActor.h
  GameEngineContents/ProcessMapInfo.cpp
  GameEngineContents/ProcessMapInfo.h
Labels: enhancement

#20 이수정 feat : 마우스로 편집기능 추가 #15
  App/imgui.ini
  GameEngineContents/MapEditorWindow.cpp
  GameEngineContents/MapEditorWindow.h
Labels: enhancement

#23 index 접근 문제 & 삭제가 되지 않는 문제 해결 #19
  ContentResources/MapInfo/new.csv
  GameEngineContents/MapEditGlobalValue.h
  GameEngineContents/MapEditorWindow.cpp
  GameEngineContents/MapEditorWindow.h
  GameEngineContents/ProcessMapInfo.cpp
Labels: enhancement

#26 이수정 refac : map editor 최적화1
  GameEngineContents/MapEditorWindow.cpp
  GameEngineContents/MapEditorWindow.h
Labels: enhancement

#27 이수정 fix : 맵 에디터 저장형식 변경&구조 수정
  GameEngineContents/GameContentsMapActor.cpp
  GameEngineContents/GameContentsMapActor.h
  GameEngineContents/GameContentsNetActor.cpp
  GameEngineContents/GameContentsNetActor.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/MapEditGlobalValue.h
  GameEngineContents/MapEditorWindow.cpp
  GameEngineContents/MapEditorWindow.h
  GameEngineContents/ProcessMapInfo.cpp
Labels: test

#29 오의현_feat : Player 기초구조 작성
  App/imgui.ini
  ContentResources/MapInfo/LevelFalling.csv
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/PlayerBase.cpp
  GameEngineContents/PlayerBase.h
  GameEngineContents/Player_Banana.cpp
  GameEngineContents/Player_Banana.h
Labels: enhancement

#31 오의현_feat : 텍스쳐가 없는 유닛을 반환하는 GetUntexturedUnit 함수 추가, 플레이어 얼굴 리소스 추가, …
  ContentResources/MapInfo/LevelFalling.csv
  ContentResources/Mesh/Characters/GetTest.fbx
  ContentResources/Texture/Face/Face0.png
  ContentResources/Texture/Face/Face1.png
  ContentResources/Texture/Face/Face10.png
  ContentResources/Texture/Face/Face11.png
  ContentResources/Texture/Face/Face12.png
  ContentResources/Texture/Face/Face13.png
  ContentResources/Texture/Face/Face14.png
  ContentResources/Texture/Face/Face15.png
  ContentResources/Texture/Face/Face2.png
  ContentResources/Texture/Face/Face3.png
  ContentResources/Texture/Face/Face4.png
  ContentResources/Texture/Face/Face5.png
  ContentResources/Texture/Face/Face6.png
  ContentResources/Texture/Face/Face7.png
  ContentResources/Texture/Face/Face8.png
  ContentResources/Texture/Face/Face9.png
  GameEngineContents/Boomerang.cpp
  GameEngineContents/Boomerang.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/PlayerBase.cpp
  GameEngineContents/PlayerBase.h
  GameEngineContents/Player_Banana.cpp
  GameEngineCore/GameEngineFBXRenderer.cpp
  GameEngineCore/GameEngineFBXRenderer.h
Labels: enhancement

#32 이수정 feat : Temporary file 생성 기능 추가
  .gitignore
  ContentResources/MapInfo/TMP/16924234271692423295Cpytest.csv
  GameEngineBase/GameEngineTime.h
  GameEngineContents/MapEditorWindow.cpp
  GameEngineContents/MapEditorWindow.h
  GameEngineContents/ProcessMapInfo.cpp
  GameEngineContents/ProcessMapInfo.h
Labels: enhancement

#34 이수정 fix : float 입력칸 작동하지 않는 문제 해결
  GameEngineContents/MapEditorWindow.cpp
Labels: bug, test

#35 오의현 : LevelFalling 배치 완료, PlayerQueue에 ItemQueue 추가, 색을 입힐 수 있는 ContentFBXRenderer 추가
  ContentResources/ContentsShader/ContentMeshShader.hlsl
  ContentResources/MapInfo/LevelFalling.csv
  ContentResources/MapInfo/TMP/16924234271692423295Cpytest.csv
  ContentResources/Mesh/Characters/Bamboo_01.fbx
  ContentResources/Mesh/Map/Bamboo_01.fbx
  ContentResources/Mesh/Map/Bamboo_Foliage_DIF.png
  ContentResources/Mesh/Map/GrassVase.fbx
  ContentResources/Mesh/Map/GrassVase_DIF.png
  ContentResources/Mesh/Map/Ocean.fbx
  ContentResources/Mesh/Map/StoneBig.fbx
  ContentResources/Mesh/Map/StoneLeaf.fbx
  ContentResources/Mesh/Map/Stone_2x2.fbx
  ContentResources/Mesh/Map/Stone_2x4.fbx
  ContentResources/Mesh/Map/StylizedBamboo_DIF.png
  ContentResources/Mesh/Map/VineAtlas_DIF.png
  ContentsShader/ContentsShader.vcxproj
  ContentsShader/ContentsShader.vcxproj.filters
  GameEngineContents/ContentFBXRenderer.cpp
  GameEngineContents/ContentFBXRenderer.h
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/Player.cpp
  GameEngineContents/PlayerBase.cpp
  GameEngineContents/PlayerBase.h
  GameEngineCore/GameEngineFBXRenderer.h
  GameEngineCore/GameEngineRenderer.cpp
  GameEngineCore/GameEngineRenderer.h
Labels: bug, enhancement

#39 이수정 feat : 서버 패킷 임시구성, 엔진구조 변경
  GameEngineBase/GameEngineNetObject.h
  GameEngineContents/ConnectIDPacket.h
  GameEngineContents/GameContentsMapActor.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/ObjectUpdatePacket.h
  GameEngineContents/PacketEnum.cpp
  GameEngineContents/PacketEnum.h
  GameEngineContents/Player.cpp
  GameEngineContents/PreCompileHeader.h
  GameEngineContents/ServerPacket.cpp
  GameEngineContents/ServerPacket.h
  GameEngineContents/ServerTestLevel.cpp
  GameEngineContents/ServerWindow.cpp
  GameEngineContents/TestObject.cpp
  GameEngineContents/TestObject.h
  GameEngineCore/GameEngineCore.cpp
  GameEngineCore/GameEngineCore.h
  GameEngineCore/GameEngineCore.vcxproj
  GameEngineCore/GameEngineCore.vcxproj.filters
  GameEngineCore/GameEngineLevel.cpp
  GameEngineCore/GameEngineLevel.h
  GameEngineCore/GameEngineNetActor.cpp
  GameEngineCore/GameEngineNetActor.h
Labels: enhancement

#40 이수정 feat : MapEditor bin to Text 추가 #30
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/MapEditorWindow.cpp
  GameEngineContents/ProcessMapInfo.cpp
  GameEngineContents/ProcessMapInfo.h
Labels: enhancement, test

#42 StartLevet, ContentTextureShader 추가
  ContentResources/ContentsShader/ContentTextureShader.hlsl
  ContentResources/Texture/UI/Logo_Arrow.png
  ContentResources/Texture/UI/Sky.png
  ContentResources/Texture/UI/Start_Cloud.png
  ContentResources/Texture/UI/Start_Ground.png
  ContentResources/Texture/UI/Start_WaterMelon.png
  ContentResources/Texture/UI/Text_BOOMEANG.png
  ContentResources/Texture/UI/Text_F.png
  ContentResources/Texture/UI/Text_U.png
  ContentResources/Texture/UI/WhiteLine.png
  ContentsShader/ContentsShader.vcxproj
  ContentsShader/ContentsShader.vcxproj.filters
  GameEngineContents/ContentSpriteRenderer.cpp
  GameEngineContents/ContentSpriteRenderer.h
  GameEngineContents/ContentsCore.cpp
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/LevelWindow.cpp
  GameEngineContents/StartLevel.cpp
  GameEngineContents/StartLevel.h
  GameEngineContents/StartUI.cpp
  GameEngineContents/StartUI.h
  GameEngineCore/GameEngineFBXMesh.cpp
Labels: enhancement

#43 이수정 refactor : 서버 패킷구조와 패킷업데이트 위치 변경
  GameEngineBase/GameEngineNetObject.cpp
  GameEngineBase/GameEngineNetObject.h
  GameEngineContents/CenterLevel.cpp
  GameEngineContents/GameContentsMapActor.cpp
  GameEngineContents/GameContentsMapActor.h
  GameEngineContents/GameContentsNetActor.cpp
  GameEngineContents/GameContentsNetActor.h
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/MapEditorLevel.cpp
  GameEngineContents/PhysXTestLevel.cpp
  GameEngineContents/ServerPacket.h
  GameEngineContents/ServerTestLevel.cpp
  GameEngineContents/StartLevel.cpp
  GameEngineContents/TestLevel.cpp
  GameEngineContents/TestObject.cpp
  GameEngineContents/TestObject.h
  GameEngineCore/GameEngineCore.cpp
  GameEngineCore/GameEngineLevel.cpp
  GameEngineCore/GameEngineLevel.h
  GameEngineCore/GameEngineNetActor.h
Labels: refactor

#45 SelectLevel 추가
  ContentResources/ContentsShader/ContentTextureShader.hlsl
  ContentResources/Texture/UI/ButtonBackGround.png
  ContentResources/Texture/UI/CharacterBackGround.png
  ContentResources/Texture/UI/FocusCircle.png
  ContentResources/Texture/UI/Logo_Fu_Highlight_0.png
  ContentResources/Texture/UI/Logo_Fu_Highlight_1.png
  ContentResources/Texture/UI/SelectCircle.png
  ContentResources/Texture/UI/Select_Avocado_Idle.png
  ContentResources/Texture/UI/Select_Avocado_Smile.png
  ContentResources/Texture/UI/Select_Bacon_Idle.png
  ContentResources/Texture/UI/Select_Bacon_Smile.png
  ContentResources/Texture/UI/Select_Banana_Idle.png
  ContentResources/Texture/UI/Select_Banana_Smile.png
  ContentResources/Texture/UI/Select_Bread_Idle.png
  ContentResources/Texture/UI/Select_Bread_Smile.png
  ContentResources/Texture/UI/Select_Carrot_Idle.png
  ContentResources/Texture/UI/Select_Carrot_Smile.png
  ContentResources/Texture/UI/Select_Coffee_Idle.png
  ContentResources/Texture/UI/Select_Coffee_Smile.png
  ContentResources/Texture/UI/Select_Donut_Idle.png
  ContentResources/Texture/UI/Select_Donut_Smile.png
  ContentResources/Texture/UI/Select_EggPlant_Idle.png
  ContentResources/Texture/UI/Select_EggPlant_Smile.png
  ContentResources/Texture/UI/Select_IceCream_Happy.png
  ContentResources/Texture/UI/Select_IceCream_Idle.png
  ContentResources/Texture/UI/Select_Sushi_Idle.png
  ContentResources/Texture/UI/Select_Sushi_Smile.png
  ContentResources/Texture/UI/Sky.png
  ContentResources/Texture/UI/Start_Avocado.png
  ContentResources/Texture/UI/Start_Bamboo1.png
  ContentResources/Texture/UI/Start_Banana.png
  ContentResources/Texture/UI/Start_BigBamboo.png
  ContentResources/Texture/UI/Start_Boomerang.png
  ContentResources/Texture/UI/Start_Bread.png
  ContentResources/Texture/UI/Start_Ground.png
  ContentResources/Texture/UI/Start_GroundShadow.png
  ContentResources/Texture/UI/Start_Ground_Back.png
  ContentResources/Texture/UI/Start_Ground_Front.png
  ContentResources/Texture/UI/Start_Slash_Effect.png
  ContentResources/Texture/UI/Start_SmallBamboo.png
  ContentResources/Texture/UI/TestGeometry.png
  ContentResources/Texture/UI/Text_F.png
  ContentResources/Texture/UI/Text_U.png
  GameEngineContents/CharacterList.cpp
  GameEngineContents/CharacterList.h
  GameEngineContents/ContentUIRenderer.cpp
  GameEngineContents/ContentUIRenderer.h
  GameEngineContents/ContentsCore.cpp
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/LevelWindow.cpp
  GameEngineContents/SelectLevel.cpp
  GameEngineContents/SelectLevel.h
  GameEngineContents/StartUI.cpp
  GameEngineContents/StartUI.h
Labels: enhancement

#48 주석추가
  ContentResources/ContentsShader/ContentMeshShader.hlsl
Labels: bug, Annotation

#50 이수정 feat : 접근한 인덱스 표시기능 업데이트 #19
  GameEngineContents/GameContentsMapActor.cpp
  GameEngineContents/GameContentsMapActor.h
  GameEngineContents/MapEditorWindow.cpp
  GameEngineContents/MapEditorWindow.h
Labels: enhancement

#65 이수정 feat : 플레이어 업데이트
  GameEngineContents/ContentsCore.cpp
  GameEngineContents/Contents_Resources.cpp
  GameEngineContents/GameEngineContents.vcxproj
  GameEngineContents/GameEngineContents.vcxproj.filters
  GameEngineContents/LevelWindow.cpp
  GameEngineContents/Player.cpp
  GameEngineContents/Player.h
  GameEngineContents/PlayerFSM.cpp
  GameEngineContents/PlayerTestLevel.cpp
  GameEngineContents/PlayerTestLevel.h
Labels: enhancement

#67 이수정 feat : GameEngineFBXRenderer 애니메이션 추가 기능 업데이트 #66
  GameEngineCore/GameEngineFBXRenderer.cpp
  GameEngineCore/GameEngineFBXRenderer.h
Labels: enhancement

#68 이수정 feat : 플레이어 애니메이션 업데이트 #58
  GameEngineContents/Player.cpp
  GameEngineContents/Player.h
  GameEngineContents/PlayerFSM.cpp
Labels: enhancement

#71 이수정 feat : 플레이어 애니메이션 수정 #58
  GameEngineBase/GameEngineMath.h
  GameEngineContents/PhysXTestLevel.cpp
  GameEngineContents/Player.cpp
  GameEngineContents/Player.h
  GameEngineContents/PlayerFSM.cpp
  GameEngineCore/GameEngineFBXRenderer.cpp
Labels: enhancement
